# Generated by Django 4.1 on 2024-06-11 09:48

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_str', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
